name: Continuous Integration Deploy

on:
  workflow_run:
    workflows:
      - "Version Bump"
    types:
      - "completed"
    

jobs:
  deploy:
    name: "Create a Deployment"
    runs-on: "ubuntu-latest"
    permissions:
      deployments: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

        - uses: actions/checkout@v2

        - uses: chrnorm/deployment-action@v2
          name: Create GitHub deployment
          id: deployment
          with:
            token: '${{ secrets.GITHUB_TOKEN }}'
            environment: test


