name: Continuous Integration Build

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile Source code
    steps:

      - uses: actions/checkout@v2

      - run: |
          echo "success"
