name: Continuous Integration Deploy Sevice

on:
  deployment:
    

jobs:
  deploy:
    name: "Deploy Service to test"
    runs-on: "ubuntu-latest"
    environment: test    
    steps:

        - uses: actions/checkout@v2

        - run: |
            echo "success"

