name: Deploy Sevice

on:
  deployment:
    
jobs:
  deploy:
    name: "Deploy Service to test"
    runs-on: "ubuntu-latest"
    environment: test
    steps:

        - uses: actions/checkout@v2

        - run: |
            echo "success"

        - name: Update deployment status (success)
          if: success()
          uses: chrnorm/deployment-status@v2
          with:
            token: '${{ secrets.GITHUB_TOKEN }}'
            state: 'success'
            deployment-id: ${{ steps.deployment.outputs.deployment_id }}

