name: Version Bump

on:
  workflow_run:
    workflows:
      - "Continuous Integration Build"
    types:
      - "completed"

jobs:
  version-bump:
    runs-on: ubuntu-latest
    name: Version Bump
    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
